package com.app.fitfusiongym.database.entities

import android.net.Uri
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a user in the database.
 *
 * @property id The unique identifier for the user. Auto-generated by the database.
 * @property name The first name of the user.
 * @property surname The last name of the user.
 * @property username The username chosen by the user. This is unique for each user.
 * @property email The email address of the user.
 * @property password The password for the user's account.
 * @property height The height of the user in centimeters.
 * @property weight The current weight of the user in kilograms.
 * @property weightGoal The target weight the user wants to achieve.
 * @property likes A list of strings representing the user's interests or preferences.
 * @property profileImageUri The URI of the user's profile image.
 */
@Entity(tableName = "user")
data class User(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val surname: String,
    val username: String,
    val email: String,
    val password: String,
    val height: Float,
    val weight: Float,
    val weightGoal: Float,
    val likes: List<String>,
    val profileImageUri: Uri?
)
